apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: sidecar
    image: appropriate/curl:latest
    command: ["sh", "-c", "while true; do curl -s http://localhost:80; sleep 5; done"]