apiVersion: v1
kind: Pod
metadata:
  name: pod-init
  namespace: default
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'echo "Initializing..."; sleep 20; echo "Initialization complete"']
  containers:
  - name: app-container
    image: busybox
    command: ['sh', '-c', 'echo "Starting main container"; sleep 3600']
