apiVersion: v1
kind: Service
metadata:
  name: webserver-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: webserver
    