apiVersion: v1
kind: Service
metadata:
  name: webserver-lb
spec:
  type: LoadBalancer
  ports:
    - port: 8881
      targetPort: 80
      protocol: TCP
  selector:
    app: webserver
    