apiVersion: v1
kind: Service
metadata:
  name: webserver-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31111
      protocol: TCP
  selector:
    app: webserver
    